using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerHealth : MonoBehaviour
{
    public static PlayerHealth instance;

    public int maxHealth, currentHealth;

    private void Awake()
    {
        instance = this;
    }
    // Start is called before the first frame update
    void Start()
    {
        currentHealth = maxHealth;
        UI.instance.healthSlider.maxValue = maxHealth;
        

    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public void DamagePlayer(int damage)
    {
        currentHealth -= damage;
    if(currentHealth <= 0 )
    {
        gameObject.SetActive(false);
        
        currentHealth = 0;
        GameManager.instance.PlayerDealth();

    }
    UI.instance.healthSlider.value = currentHealth;
    UI.instance.healthText.text = "HEALTH: " + currentHealth + "/" + maxHealth;
    
    }

    public void HealPlayer(int heal)
    {
        currentHealth += heal;

        if(currentHealth > maxHealth){
            currentHealth = maxHealth;
        }
    UI.instance.healthSlider.value = currentHealth;
    UI.instance.healthText.text = "HEALTH: " + currentHealth + "/" + maxHealth;
    }
}
